spring:
  application:
    name: tavia-traffic-simulator
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: tavia-config-service
