server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tavia_db
    username: tavia_user
    password: tavia_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
