spring:
  application:
    name: tavia-traffic-simulator
  main:
    allow-bean-definition-overriding: true

server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.tavia: DEBUG
    org.springframework.web: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

simulator:
  cycle-delay-ms: 8000
